CREATE TABLE [dbo].[Date] (
    [PKDate]                    DATE          NOT NULL,
    [calendar_day_in_month]     TINYINT       NULL,
    [calendar_day_in_week]      TINYINT       NULL,
    [calendar_day_in_year]      SMALLINT      NULL,
    [calendar_month]            TINYINT       NULL,
    [calendar_month_name_long]  VARCHAR (30)  NULL,
    [calendar_month_name_short] VARCHAR (10)  NULL,
    [calendar_quarter]          TINYINT       NULL,
    [calendar_quarter_desc]     VARCHAR (10)  NULL,
    [calendar_week_in_month]    TINYINT       NULL,
    [calendar_week_in_year]     TINYINT       NULL,
    [calendar_year]             SMALLINT      NULL,
    [continuous_day]            INT           NULL,
    [continuous_month]          SMALLINT      NULL,
    [continuous_quarter]        SMALLINT      NULL,
    [continuous_week]           SMALLINT      NULL,
    [continuous_year]           TINYINT       NULL,
    [day_name_long]             VARCHAR (10)  NULL,
    [day_name_short]            VARCHAR (10)  NULL,
    [description]               VARCHAR (100) NULL,
    [is_event]                  TINYINT       NULL,
    [is_holiday]                TINYINT       NULL,
    [is_weekend]                TINYINT       NULL,
    [is_workday]                TINYINT       NULL,
    [mdy_name_long]             VARCHAR (30)  NULL,
    [mdy_name_long_with_suffix] VARCHAR (30)  NULL,
    CONSTRAINT [PK_Date] PRIMARY KEY CLUSTERED ([PKDate] ASC)
);

